FROM node:16-alpine

ENV YARN_VERSION 1.22.19

# Install Useful Tools
RUN apk --no-cache upgrade && \
  apk --no-cache add git gnupg wget curl jq bash tar openssl util-linux postgresql-client ca-certificates curl gnupg nano zsh-syntax-highlighting less procps lsof && \
  npm install -g expo-cli

# Install zsh-in-docker
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v${ZSH_IN_DOCKER_VERSION}/zsh-in-docker.sh)" -- \
  -t clean \
  -p git \
  -p node \
  -p yarn \
  -p history \
  -p https://github.com/zsh-users/zsh-autosuggestions \
  -p https://github.com/zsh-users/zsh-completions
RUN echo "source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> /root/.zshrc

# Set yarn version
RUN yarn set version ${YARN_VERSION}

# Working directory inside container
WORKDIR /app